broker:
  br_address: "127.0.0.1"
  br_port: 1883
  br_use_ssl: false

database:
  db_name: "afm"
  db_user: "someone"
  db_password: "yours"
  db_host: "127.0.0.1"
  db_port: 3306
  db_type: "mysql"

website:
  ws_host: "127.0.0.1"
  ws_port: 8080
  ws_root: "./web"

log:
  settings:
    level: "Information"
    trigger_level: "Error"
    backlog: 500
  formatters:
    -
      id: text
      filename: "camera.log"