# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: build
    silent: true
  build:
    cmds:
      - go build -o camera cmd/main.go
  lint:
    cmds:
      - golangci-lint run cmd/main.go